@startuml

autonumber
actor Client
participant Mailing
participant Website
participant "Azure function" as AF
participant "Azure queue storage" as AQ

Client -> Mailing : open
Mailing -> Website : afmelden met code
Website -> AF : afmeldcode 
AF -> AQ : afmeldcode 
AQ --> AF : geaccepteerd
AF --> Website : geaccepteerd
Website -> Website : doorsturen naar pagina
Website -> Client : bevestiging

@enduml